#### Ödev 1
1. Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

2. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [132]:
import numpy as np

matris = np.array([7, 11, 15, 19, 23, 27, 31], dtype=int)

print("Matris:", matris)
print("Boyut:", matris.shape)
print("Eleman sayısı:", matris.size)

Matris: [ 7 11 15 19 23 27 31]
Boyut: (7,)
Eleman sayısı: 7


#### Ödev 2
Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

In [134]:
import numpy as np

matris2 = np.array([[1, 2, 6, 7],
                   [4, 3, 9, 5]])

print("İki boyutlu matris:")
print(matris2)
print(" ")
print("Boyut:", matris2.ndim)
print("Eleman sayısı:", matris2.size)
print("Satır ve sütun bilgisi:", matris2.shape)

İki boyutlu matris:
[[1 2 6 7]
 [4 3 9 5]]
 
Boyut: 2
Eleman sayısı: 8
Satır ve sütun bilgisi: (2, 4)


In [136]:
import numpy as np

matris3 = np.array([[[7, 5, 14],
                     [21, 8, 11]],
                    [[8, 6, 20],
                     [14, 3, 9]]])

print("Üç boyutlu matris:")
print(matris3)
print(" ")
print("Boyut:", matris3.ndim)
print("Eleman Sayısı:", matris.size)
print("Satır ve sütun bilgisi:", matris3.shape)

Üç boyutlu matris:
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
 
Boyut: 3
Eleman Sayısı: 7
Satır ve sütun bilgisi: (2, 2, 3)


#### Ödev 3
İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

1. İki boyutlu arraydaki 2 elemanına ulaşalım.

2. İki boyutlu arraydaki 7 elemanına ulaşalım.

3. Üç boyutlu arraydaki 9 elemanına ulaşalım.

4. Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [138]:
import numpy as np

matris2 = np.array([[1, 2, 6, 7],
                   [4, 3, 9, 5]])
matris2[0,1]

2

In [140]:
import numpy as np

matris2 = np.array([[1, 2, 6, 7],
                   [4, 3, 9, 5]])
matris2[0,3]

7

In [142]:
import numpy as np

matris3 = np.array([[[7, 5, 14],
                     [21, 8, 11]],
                    [[8, 6, 20],
                     [14, 3, 9]]])
matris3[1,1,2]

9

In [144]:
import numpy as np

matris3 = np.array([[[7, 5, 14],
                     [21, 8, 11]],
                    [[8, 6, 20],
                     [14, 3, 9]]])
matris3[0,0,1]

5

#### Ödev 4
Arrayler üzerinde slicing işlemi uygulayalım.

1. İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

2. İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

3. Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

4. Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

In [146]:
import numpy as np

matris2 = np.array([[1, 2, 6, 7],
                   [4, 3, 9, 5]])
matris2[0:1,1:3]

array([[2, 6]])

In [148]:
import numpy as np

matris2 = np.array([[1, 2, 6, 7],
                   [4, 3, 9, 5]])
matris2[1:2,1:4]

array([[3, 9, 5]])

In [150]:
import numpy as np

matris3 = np.array([[[7, 5, 14],
                     [21, 8, 11]],
                    [[8, 6, 20],
                     [14, 3, 9]]])
matris3[0:1,1:2,0:3]

array([[[21,  8, 11]]])

In [152]:
import numpy as np

matris3 = np.array([[[7, 5, 14],
                     [21, 8, 11]],
                    [[8, 6, 20],
                     [14, 3, 9]]])
matris3[1:2,0:1,1:3]

array([[[ 6, 20]]])

#### Ödev 5
5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [154]:
import numpy as np

sifir = np.zeros((5,3), dtype = "int")
print("0 matrisi:")
print(sifir)

bir = np.ones((5,3), dtype = "int")
print("1 matrisi:")
print(bir)

satir = np.concatenate([sifir,bir], axis = 0)
print("Satır bazında birleşme:")
print(satir)

sutun = np.concatenate([sifir,bir], axis = 1)
print("Sütun bazında birleşme:")
print(sutun)

0 matrisi:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
1 matrisi:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Satır bazında birleşme:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleşme:
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
